### ISSUE TITLE
Guide to v5 beta

### ISSUE THREAD

**Issue by NicEastvillage** [RLBot/core#43]
This issue is a WIP description of v5 (beta) and will contain 
- Our reasoning for creating v5 and an overview of its architecture
- A list of features completed/reworked/todo/removed in v5 (beta)
- A guide on how to transition from v4 to v5

## Architecture of v5

TODO

## Features of v5

Legend: ✅=done, 🟨=todo, ✨=new, 🛠=reworked/changed, ⛔=removed

- ✅🛠 First-class Windows & Linux support
  - No current plans for MacOS, as there's no way to run Rocket League without a VM
- ✅🛠 All bots connect to core directly via the [sockets spec](https://github.com/RLBot/flatbuffers-schema)
  - As a consequence, adding new language support is _much_ easier - if your language can write/read a TCP socket, it's possible! Bonus points if your language is one of the 14 that are currently supported by [FlatBuffers](https://flatbuffers.dev/usergroup0.html)
- ✅🛠 Any language can start/stop/manage a match
- ✅🛠 All configs files now use the standard `toml` format. Example: [necto/bot.toml](https://github.com/VirxEC/python-interface/blob/master/tests/necto/bot.toml)
- ✅ Hiveminds
- ✅ Scripts
- ✅🛠 The bot configuration's `python_file` has been replaced with `run_command` and `run_command_linux`
  - 🟨 On Linux, if `run_command_linux` isn't specified, v5 will attempt to run `run_command` under Wine
- ✅✨ Multi-ball support for when there's more/less than 1 ball in a game
- ✅✨ New mutator options
  - Start with one, two, four, or six balls
  - Max 7 goals
  - Beach ball, anniversary ball, or the haunted dropshot ball
  - Curve ball or beach ball curve
  - Reverse gravity
  - Tactical rumble (fyi we still can't read rumble items)
- ✅✨ Freeplay matches. Useful if you want to use the Rocket League's freeplay-exclusive features
- ✅ Rendering
  - 🟨 Rendering can be toggled for individual bots
  - 🟨(maybe ⛔) Keyboard shortcuts to toggle rendering. We plan to have buttons in the GUI instead
  - ✅ ✨ New `RenderAnchor`s. Attach your rendering to the location and rotation of a car or ball plus both an absolute and local offset. No re-rendering is required and it is _smooth_. Example: [video posted on Discord](https://discord.com/channels/348658686962696195/423167304956903428/1254229014084714577)
- ✅ Game state manipulation (aka state setting)
- ✅ Updated ball prediction algorithm for better accuracy in all game modes that use a ball
- ✅✨ Support for Psyonix Beginner bots
- 🟨✨ More customizable Psyonix bots
- ✅✨ Override a bot name/loadout (without editing the bot configuration)
  - Use cases include: Spawning specific Psyonix bots or give Nexto your ingame name to troll friends
- 🟨🛠 Generated loadouts are now created by your bot instead of a separated loadout generator script
- 🟨✨ Hot-swap your bot's loadout. Respawn your bot's car with a different loadout on command without restarting the match or interfering with the other bots
  - Only enabled when state setting is also enabled
- ✅✨ New data in `GameTickPacket` for every player:
  - Last known player input
  - If the player was the last player to be spectated in the match
  - Player accolades. A list of small awards/events by the player, e.g. EpicSave, Demolition, PoolShot, LowFive, etc. See [full list here](https://github.com/RLBot/flatbuffers-schema/blob/fc972ab24893a44f6df316c41d3eaf12b0c8ead1/rlbot.fbs#L144-L156))
- ✅🛠 Match comms and quick chat have been combined into just `MatchComm`s with an optional quick chat message such that both bots and humans can understand what is meant
  - ⛔ Quick chat messages are no longer restricted to a set of hardcoded options
  - ✅🛠 The `team_only` filtering finally works. No more spying on enemy chats
- 🟨🛠 RLBot waits for all processes to fully boot before letting the match start
- 🟨 Performance metrics (i.e. missed responses by bots)
- ⛔ Non-standard Tick Rates (standard is 120hz)
- ⛔ DropshotTileInfo (will hopefully return!)

On top of all that, the framework is also simply significantly faster.

## Transitioning from v4 to v5

TODO

**Comment by VirxEC** [comment]
would a wiki page for this be better?

**Comment by NicEastvillage** [comment]
Initially, this information will be too dynamic for a wiki page, but eventually, it would make sense to move it. In any case, this issue will track the task of creating this info.

**Comment by VirxEC** [comment]
should architecture be for core, or for how an interface works? I think the latter would be better

**Comment by swz-git** [comment]
i was thinking both

**Comment by VirxEC** [comment]
New features in v5:
- First-class Windows & Linux support
  - No current plans for MacOS, as there's no way to run Rocket League without a VM
- Minimal closed-source `Bridge.dll`, unlike v4 where the entirety of `RLBot.exe` was closed source
- All bots connect to core directly via the [sockets spec](https://github.com/RLBot/flatbuffers-schema)
- Adding new language support is _much_ easier - if your language can write/read a TCP socket, it's possible!
  - Bonus points if your language is one of the 14 that are currently supported by [FlatBuffers](https://flatbuffers.dev/usergroup0.html)
  - A popular language will likely have a "language interface" (e.x. [python-interface](https://github.com/VirxEC/python-interface) or [rust-interface](https://github.com/swz-git/rust-interface)) that are relatively minimal libraries on top of the RLBot v5 spec but will greatly simplify the process of creating bots
- Any language can start/stop/manage a match
  - In general, starting a match is _much_ faster
- All configs files current used the standard `toml` format
  - Support for other config formats like YAML and JSON are possible to add in the future
- Hiveminds are an official feature
- Scripts are an official feature
- `python_file` has been replaced with `run_command` and `run_command_linux`
  - In the future, if `run_command_linux` isn't specified, v5 will attempt to run `run_command` under Wine
- Multi-ball support for when there's more/less than 1 ball in a game
- New mutator options
  - Start with one, two, four, or six balls
  - Max 7 goals
  - Beach ball, anniversary ball, or the haunted dropshot ball
  - Curve ball or beach ball curve
  - Reverse gravity
  - Tactical rumble (fyi still can't read rumble items)
- New option to load the match in freeplay instead of it being an exhibition match
  - Useful if you just want to mess around and use the Rocket League's freeplay exclusive features
- New `RenderAnchor`s
  - `world` - `Vector3` that is a global coordinate offset reminiscent of what's currently in v4
  - `relative` - A physics object to treat as `(0, 0, 0)`, position of the point will follow relative to the position and rotation of the physics object each frame without requesting a re-render
    - Can be `CarAnchor` or `BallAnchor` - Takes the `index` of the ball or car in the `GameTickPacket` that the point should be relative to and `local` which is another `Vector3` that is the offset of the point relative to the rotation of the object
  - `world` and `relative` can be combined to do things like render to a point that's 100 units above the specified ball
  - For an example, see [this video](https://discordapp.com/channels/348658686962696195/423167304956903428/1254233700468785267) and [the code behind it](https://github.com/VirxEC/python-interface/blob/2a11dbac49736054046323f1d3311655a84f4f41/tests/render_test/render.py#L32
)
- Updated ball prediction algorithm for better accuracy in all game modes that use a ball
- More customizable Psyonix bots (coming _very_ soon but not public yet)
  - Allow spawning Psyonix Beginner
  - Can specify a `bot.toml` file to customize the following
  - Custom name support
    - If the name matches a Psyonix preset's name, e.x. "Boomer", then that preset will be used
  - Custom loadout support
  - Can specify an accompanying script to the Psyonix bot
    - Scripts gets passed the details of the Psyonix bot in the `GameTickPacket`
    - Can be used for dynamic, custom Psyonix bot loadout generators
    - Can also be used for anything you want!
- Hot-swap your bot's loadout (coming soon)
  - Only enabled when state setting is also enabled
  - Same message is used for loadout generator support but is only enabled before the match starts
    - Loadout generators are no longer a separate process from your bot
  - Allows respawning your bot's car with a different loading, on command, without restart the match or interfering with the other bots
- New data in `GameTickPacket` for every player:
  - Last known player input
    - Works for _every_ player on the field, including LAN connected humans
    - No guarantee to how new/old the data is as that's untested. Be the first!
  - If the player was the last player to be spectated in the match
  - Player accolade info (see [this list](https://github.com/RLBot/flatbuffers-schema/blob/fc972ab24893a44f6df316c41d3eaf12b0c8ead1/rlbot.fbs#L144-L156))
- Match comms and quick chat have been combined into just `MatchComm`s
  - Custom quick chat-style display messages
  - Messages contents are sent in binary format, allowing for custom formats that aren't JSON
  - `team_only` messages are properly filtered! For scripts, `team_only` messages are only sent to other scripts
- RLBot waits for all processes to fully boot before letting the match start
  - To clarify, the match will be _loaded_ and cars spawned in, but the kickoff will not start

**Comment by VirxEC** [comment]
Architecture:
Google doc that can be copied then edited: https://drive.google.com/file/d/13LW0l7nzc_dbwgT20cGHywx_5vNu4RTc/view?usp=sharing

Svg:
![RLBot v5](https://github.com/user-attachments/assets/5bbb7447-012c-4eeb-819c-59100f9a990b)

Png:
![RLBot v5](https://github.com/user-attachments/assets/6cfdb2bb-29b9-4cb8-9fca-d6b12c986997)

**Comment by NicEastvillage** [comment]
Overview has been moved to wiki. See https://github.com/RLBot/wiki/pull/7
